name       : pantheon-files
version    : 0.3.4
release    : 3
source     :
    - https://launchpad.net/pantheon-files/0.3.x/0.3.4/+download/pantheon-files-0.3.4.tar.xz : 93b62388aea58deda0b288eb54dedc73b1cd6cefbce0f2bc516f9bb18715e744
license    : GPL-3.0
component  : desktop
summary    : The simple, powerful, and sexy file manager from elementary
description: |
    The simple, powerful, and sexy file manager from elementary
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(granite)
    - pkgconfig(gail-3.0)
    - pkgconfig(libcanberra)
    - pkgconfig(sqlite3)
    - pkgconfig(zeitgeist-2.0)
    - pkgconfig(libnotify)
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    # install select icons missing from most icon packs
    for i in $pkgfiles/16x16/actions/*; do
        install -Dm 00644 $i $installdir/usr/share/icons/hicolor/16x16/actions/${i##*/}
    done;
    for i in $pkgfiles/24x24/actions/*; do
        install -Dm 00644 $i $installdir/usr/share/icons/hicolor/24x24/actions/${i##*/}
    done;

    %make_install
