name       : pantheon-files
version    : 0.3.5
release    : 8
source     :
    - git|https://github.com/elementary/files.git : 7b7ac1c5222a1eb7b917a1f179008f3357507386
license    : GPL-3.0-or-later
component  : desktop
summary    : The simple, powerful, and sexy file manager from elementary
description: |
    The simple, powerful, and sexy file manager from elementary
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gail-3.0)
    - pkgconfig(granite)
    - pkgconfig(libcanberra)
    - pkgconfig(libnotify)
    - pkgconfig(sqlite3)
    - pkgconfig(zeitgeist-2.0)
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    # install select icons missing from most icon packs
    for i in $pkgfiles/16x16/actions/*; do
        install -Dm 00644 $i $installdir/usr/share/icons/hicolor/16x16/actions/${i##*/}
    done;
    for i in $pkgfiles/24x24/actions/*; do
        install -Dm 00644 $i $installdir/usr/share/icons/hicolor/24x24/actions/${i##*/}
    done;

    %make_install
