name       : pantheon-files
version    : 4.1.7
release    : 9
source     :
    - https://github.com/elementary/files/archive/4.1.7.tar.gz : ec773acfe35aaa5315a9a1430822892a960b14f756dc81e16b1a1f242b62bbc0
license    : GPL-3.0-or-later
component  : desktop
summary    : The simple, powerful, and sexy file manager from elementary
description: |
    The simple, powerful, and sexy file manager from elementary
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gail-3.0)
    - pkgconfig(granite)
    - pkgconfig(libcanberra)
    - pkgconfig(libnotify)
    - pkgconfig(sqlite3)
    - pkgconfig(zeitgeist-2.0)
    - vala
setup      : |
    %meson_configure -Dwith-unity=false
build      : |
    %ninja_build
install    : |
    # install select icons missing from most icon packs
    for i in $pkgfiles/16x16/actions/*; do
        install -Dm 00644 $i $installdir/usr/share/icons/hicolor/16x16/actions/${i##*/}
    done;
    for i in $pkgfiles/24x24/actions/*; do
        install -Dm 00644 $i $installdir/usr/share/icons/hicolor/24x24/actions/${i##*/}
    done;

    %ninja_install
